### ISSUE TITLE
Missing book 8

### ISSUE THREAD

**Issue by mikix** [tonib/kaichronicles#3]
I know this is a known gap.  I'm just opening this github issue so that there is one central place to discuss the work needed.

I plan to start looking into it.  If someone else has already started, let me know!

**Comment by tonib** [comment]
Hello, somebody asked to work on book 9, nobody else is currently working on book 8.
Thank you!

**Comment by tonib** [comment]
I have already added a link to a "Tests" page on the debug options. There you can test the current book (and all books). The current tests do: 
* A XSD verification of the mechanics XML file. 
* Additional tests for rules. This is currently unfinished, and, right now, only checks "pick", "randomTable" and "case" rules. I will add checks for all rules here, but right now is working.

I have run run the tests over the book 8 at your fork. What I got:

mechanics-8.xml:370: element combat: Schemas validity error : Element 'combat', attribute 'mindblastMultiplier': The attribute 'mindblastMultiplier' is not allowed.
mechanics-8.xml:455: element combat: Schemas validity error : Element 'combat', attribute 'mentalOnly': The attribute 'mentalOnly' is not allowed.
mechanics-8.xml:825: element sell: Schemas validity error : Element 'sell', attribute 'class': The attribute 'class' is not allowed.
mechanics-8.xml:825: element sell: Schemas validity error : Element 'sell', attribute 'except': The attribute 'except' is not allowed.
mechanics-8.xml:825: element sell: Schemas validity error : Element 'sell': The attribute 'objectId' is required but missing.
mechanics-8.xml:906: element combatSkill: Schemas validity error : Element 'combatSkill', attribute 'toast': The attribute 'toast' is not allowed.

I guess they are exceptions (all books have A LOT of exceptions). I'll implement them later. I'll continue with additional tests

Cheers!

**Comment by mikix** [comment]
Nice. Some of those are expected (new features I’ve had to add).

I got distracted from book 8 to do a rework of how quivers work. Book 8 finally introduces rules about how they work (two books after they were introduced and very casually in a footnote of one of the sections...) Specifically, a quiver can only hold six arrows. And if you want to carry more, you can carry multiple quivers. Which is a fun mental image.

**Comment by tonib** [comment]
Burrrfff... Right now there is only a counter for arrows. Even more, on the original Action Chart (https://projectaon.org/en/xhtml/lw/08tjoh/action.htm) , there is ONE box where to write the amount of arrows

Right now you cannot pick "standalone" arrows, only quivers with an amount of arrows. Maybe you should, and if you don't have quivers enough, you should not be able to pick that arrows. When you render the objects tables, then you can assign the arrows to each quiver (same to drop quivers). 

I did not read the book 8 yet, so i cannot help you more. If you have doubts, or you do not want to implement it, don't worry, I'll check it

Lone Wolf is the book HERO, so he can carry 12 quivers (Special Items), 72 arrows (12 quivers x 6 arrows), a two-handed Weapon on each hand, and a Backpack full with 8 Ropes without breaking a sweat. Examples:
* https://pbs.twimg.com/media/CBgx7haUIAAIfqY.jpg
* http://static5.businessinsider.com/image/554bb4d96da811d154adfd51-1200/overloaded.jpg

No mock about our HERO!

By the way:
- Extra tests for mechanics done. Checked on book 8 and got the same errors, no more.
- Starting from book 8, the max. number of Special Items is 12 (Equipment section). Going to implement that.
- Due to the Special Items limit on this book, I cannot no longer delay the implementation of the "safekeeping at the Kai Monastery" referenced on the Equipment sections of the last books. Going to implement that.

**Comment by tonib** [comment]
Hi Michael:

I have added you as mechanics author to the "About the book". Do you want a link to somewhere (your Twitter / Facebook / whatever)?

Are you still interested on implementing book 8? If you don't, it's OK, I'll continue. Otherwise, I'll start with book 10.

Cheers!

**Comment by mikix** [comment]
Ugh yeah I still intend to work on this, I’ve just gotten distracted.

But if I’m blocking progress on new books, continue my work. I’ll try to get back to this though.

**Comment by tonib** [comment]
No problem, I'll start with book 10 (I got bored of implement TODOs)

**Comment by mikix** [comment]
Heyo!  My professional situation changed back in November and I've not had the free time I used to.  Consider me not actively working on this (but please steal my work in progress branch -- I just pushed what was sitting on my drive, up to about sect250, though there are some TODOs marked).

**Comment by tonib** [comment]
Uep!  I'm going to steal it. Good luck with your new situation, and thank you

**Comment by tonib** [comment]
Book 8 published on Google Play
