### ISSUE TITLE
Book 5 (Part 1), 'Rope' backpack item does not disappear when used in the sewers

### ISSUE THREAD

**Issue by mozzribo** [tonib/kaichronicles#9]
Forgot the name of the sewers, sorry. There is a choice-branch within the sewer chase part when Lone Wolf can swing across but only if he/she is in possession of a rope. Now, just before entering the sewers (at least through the church cellar) there is a rope that can be taken. However, a rope can be present from previous adventures as well, so the one offered in book 5 can be ignored, and the sewer can still be swung across. This is what I did. Then, the text notes that the rope is left to hang there, not to be retrieved and lost from the inventory.  However, the rope remained in the inventory, so I had to delete it manually.

**Comment by tonib** [comment]
Hi. I have been checking that, and I'm not sure what is the place you refer to. I have found two places where you drop a rope:

* Section 29 (https://projectaon.org/en/xhtml/lw/05sots/sect29.htm)
* Section 305 (https://projectaon.org/en/xhtml/lw/05sots/sect305.htm)

If you are talking about section 29, and the Rope was picked on book 3, you are right, it was not dropped. I will fix this. On book 2, the rope is a different object than other books, because it counts as 2 items on Backpack. On other books the Rope it counts as one item.

If it's not that section, please, check https://www.projectaon.org/en/xhtml-less-simple/lw/05sots/title.htm , try to search "rope". It would be a great help to know in which section is the bug.

**Comment by mozzribo** [comment]
It was section 29, although I haven't played the 305, so I cannot know if that happens there as well. But 29, for sure. ;)  And, yes, the rope was picked in book 3 (in the mines), so I didn't take the one offered in book 5 since I already had the one from before.

**Comment by tonib** [comment]
OK, then it will be fixed on next release.
Thank you!
